### ISSUE TITLE
PDF viewer broken

### ISSUE THREAD

**Issue by simonhurtz** [brookhong/Surfingkeys#479]
I can't view any PDFs with the Surfingkeys extensions enabled. When I activate the integrated PDF viewer the text gets unreadable:
![2017-09-11 16 53 25](https://user-images.githubusercontent.com/31856294/30281133-e61efb72-9711-11e7-8b93-ab0d59aa5991.jpg)

When I deactivate the integrated PDF viewer and try to use Chrome's native one, I only see a black page: 
![2017-09-11 16 52 12](https://user-images.githubusercontent.com/31856294/30281204-1302f3f0-9712-11e7-82d4-fd75daaf7e11.jpg)

Everything works fine in an incognito window (i.e. without Surfingkeys): 
![2017-09-11 16 53 28](https://user-images.githubusercontent.com/31856294/30281216-1c84c7f0-9712-11e7-83d5-920b312f29a5.jpg)

It's not related to any other extension, as disabling Surfingkeys completely solves the problem instantly. Is it a common bug or rather my fault? (I didn't change the default configuration except from disabling some key mappings. Reinstalling the extension didn't help either.)

**Comment by brookhong** [comment]
Thanks.

Fixed in 0.9.8

**Comment by Leoongithub** [comment]
![image](https://user-images.githubusercontent.com/10937162/30511643-5f6d7024-9b10-11e7-97cc-7e07375223cb.png)
我这里还是不能看pdf（截图为0.9.8，0.9.8之前的版本也不行），但是切换到chrome的pdf阅读器是正常的。

**Comment by Harjot1Singh** [comment]
I'm also having problems with it

**Comment by SaiHappyDay** [comment]
Updating chrome (to version 62 on Linux) solved this issue for me.

**Comment by dansbandit** [comment]
It is still broken for me. I'm on Google Chrome Version 62.0.3202.75 (Official Build) (64-bit) and Windows 10.

Example pdf: https://cseweb.ucsd.edu/~hovav/dist/rop.pdf

The example pdf gives me lines.

![pdfjsinchrome](https://user-images.githubusercontent.com/4530687/32109312-a75ca91a-bb34-11e7-92a2-a2201955dc51.png)

However it works on Google Canary Version 64.0.3250.0 (Official Build) canary (64-bit).

![pdfjsincanary](https://user-images.githubusercontent.com/4530687/32109313-a77eff06-bb34-11e7-973d-b663507a24b3.png)

The [PDF Viewer](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm/reviews) viewer extension displays the pdf correctly.

I have tried to disable hardware acceleration and 2d canvas but the problem remains. The problem remains in Chrome Beta as well.

**Comment by bara0** [comment]
surfingkeys cant render pdf corectly.
